ARG NODE_VERSION

FROM node:$NODE_VERSION

RUN apt-get update && apt-get install -y \
	gettext \
	openssh-server \
	vim

RUN mkdir /usr/frontend/
RUN mkdir /usr/frontend/node_modules/

WORKDIR /usr/frontend/

COPY ./package*.json ./
COPY ./tsconfig.json ./
COPY ./next.config.js ./
COPY ./*config* ./
COPY ./.env_temp ./

RUN npm install

COPY ./entrypoint.sh ./

ENTRYPOINT ["bash", "entrypoint.sh"]
