ARG NODE_VERSION

FROM node:$NODE_VERSION

RUN apt-get update && apt-get install -y \
	gettext

RUN mkdir /usr/frontend/
RUN mkdir /usr/frontend/node_modules/

WORKDIR /usr/frontend/

COPY ./resource ./
COPY ./entrypoint.sh ./

RUN npm install
RUN npm run build

ENTRYPOINT ["bash", "entrypoint.sh"]
