import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
	<link rel="icon" href="favicon.ico" />
	<meta
	  name="transcendence"
	  content="transcendencetranscendencetranscendence"
	/>
      </Head>
      <body className={`${inter.className} full-background`}>
	{children}
      </body>
    </html>
  )
}
// if NavBar has textContent(the text between opening tag and closing tag) the text is considered as child node
// and it requires for NavBar component to include chlidNode in its props.
