import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthContextProvider from '@/components/user/auth';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
				<link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.className} full-background`}>
				<AuthContextProvider>
					{children}
				</AuthContextProvider>
      </body>
    </html>
  )
}
// if NavBar has textContent(the text between opening tag and closing tag) the text is considered as child node
// and it requires for NavBar component to include chlidNode in its props.
